# add your settings here (overriding the defaults)

biocypher:
  offline: true
  debug: false
  head_ontology: 
    url: https://raw.githubusercontent.com/EBISPOT/hancestro/main/hancestro.owl
    root_node: ancestry category

neo4j:
  delimiter: '\t'
  array_delimiter: '|'
  skip_duplicate_nodes: true
  skip_bad_relationships: true
